import { Product } from "@/lib/types";
import { slugify } from "@/lib/utils";

export const products: Product[] = [
  {
    id: "1",
    title: "Premium Wireless Headphones",
    slug: slugify("Premium Wireless Headphones"),
    description:
      "Noise-cancelling wireless headphones with 30-hour battery life",
    price: 299.99,
    originalPrice: 399.99,
    image: "/images/headphones.jpg",
    images: ["/images/headphones-1.jpg", "/images/headphones-2.jpg"],
    category: "audio",
    inventory: 15,
    rating: 4.5,
    reviewCount: 128,
    tags: ["wireless", "noise-cancelling", "bluetooth"],
  },
  {
    id: "2",
    slug: slugify("Mechanical Gaming Keyboard"),
    title: "Mechanical Gaming Keyboard",
    description:
      "RGB mechanical keyboard with customizable switches and anti-ghosting",
    price: 129.99,
    originalPrice: 159.99,
    image: "/images/keyboard.jpg",
    images: ["/images/keyboard-1.jpg", "/images/keyboard-2.jpg"],
    category: "computers",
    inventory: 22,
    rating: 4.3,
    reviewCount: 89,
    tags: ["gaming", "rgb", "mechanical", "keyboard"],
  },
  {
    id: "3",
    slug: slugify("Wireless Gaming Mouse"),
    title: "Wireless Gaming Mouse",
    description:
      "High-precision wireless mouse with customizable DPI and ergonomic design",
    price: 79.99,
    originalPrice: 99.99,
    image: "/images/mouse.jpg",
    images: ["/images/mouse-1.jpg", "/images/mouse-2.jpg"],
    category: "computers",
    inventory: 30,
    rating: 4.6,
    reviewCount: 156,
    tags: ["gaming", "wireless", "ergonomic", "mouse"],
  },
  {
    id: "4",
    slug: slugify("Smartphone 128GB"),
    title: "Smartphone 128GB",
    description:
      "Latest smartphone with triple camera system and 5G connectivity",
    price: 899.99,
    originalPrice: 999.99,
    image: "/images/phone.jpg",
    images: ["/images/phone-1.jpg", "/images/phone-2.jpg"],
    category: "mobile",
    inventory: 12,
    rating: 4.7,
    reviewCount: 203,
    tags: ["smartphone", "5g", "camera", "android"],
  },
  {
    id: "5",
    slug: slugify("Fitness Smartwatch"),
    title: "Fitness Smartwatch",
    description:
      "Advanced smartwatch with heart rate monitoring, GPS, and sleep tracking",
    price: 199.99,
    originalPrice: 249.99,
    image: "/images/smartwatch.jpg",
    images: ["/images/smartwatch-1.jpg", "/images/smartwatch-2.jpg"],
    category: "wearables",
    inventory: 18,
    rating: 4.2,
    reviewCount: 94,
    tags: ["fitness", "smartwatch", "health", "tracking"],
  },
  {
    id: "6",
    slug: slugify("Wireless Earbuds"),
    title: "Wireless Earbuds",
    description:
      "True wireless earbuds with charging case and 24hr battery life",
    price: 149.99,
    originalPrice: 199.99,
    image: "/images/earbuds.jpg",
    images: ["/images/earbuds-1.jpg", "/images/earbuds-2.jpg"],
    category: "audio",
    inventory: 35,
    rating: 4.4,
    reviewCount: 178,
    tags: ["wireless", "earbuds", "bluetooth", "portable"],
  },
  {
    id: "7",
    slug: slugify("Wireless Phone Charger"),
    title: "Wireless Phone Charger",
    description:
      "Fast-charging wireless pad compatible with all Qi-enabled devices",
    price: 49.99,
    originalPrice: 69.99,
    image: "/images/charger.jpg",
    images: ["/images/charger-1.jpg", "/images/charger-2.jpg"],
    category: "accessories",
    inventory: 42,
    rating: 4.3,
    reviewCount: 112,
    tags: ["charging", "wireless", "fast-charge", "qi"],
  },
  {
    id: "8",
    slug: slugify("Laptop Stand Aluminum"),
    title: "Laptop Stand Aluminum",
    description:
      "Adjustable aluminum laptop stand for better ergonomics and cooling",
    price: 59.99,
    originalPrice: 79.99,
    image: "/images/laptop-stand.jpg",
    images: ["/images/laptop-stand-1.jpg", "/images/laptop-stand-2.jpg"],
    category: "computers",
    inventory: 25,
    rating: 4.5,
    reviewCount: 67,
    tags: ["laptop", "stand", "ergonomic", "aluminum"],
  },
  {
    id: "9",
    slug: slugify("Portable SSD 1TB"),
    title: "Portable SSD 1TB",
    description:
      "High-speed portable solid state drive with USB-C connectivity",
    price: 129.99,
    originalPrice: 159.99,
    image: "/images/ssd.jpg",
    images: ["/images/ssd-1.jpg", "/images/ssd-2.jpg"],
    category: "storage",
    inventory: 20,
    rating: 4.8,
    reviewCount: 145,
    tags: ["storage", "portable", "ssd", "fast"],
  },
  {
    id: "10",
    slug: slugify("Bluetooth Portable Speaker"),
    title: "Bluetooth Portable Speaker",
    description:
      "Waterproof portable speaker with 360° sound and 20-hour battery",
    price: 89.99,
    originalPrice: 119.99,
    image: "/images/speaker.jpg",
    images: ["/images/speaker-1.jpg", "/images/speaker-2.jpg"],
    category: "audio",
    inventory: 19,
    rating: 4.7,
    reviewCount: 145,
    tags: ["speaker", "portable", "waterproof", "bluetooth"],
  },
];
